/**
 * Investment
 * 投资事件  * 默认域名： service-m5j3awiv-1259459016.ap-shanghai.apigateway.myqcloud.com/release * 自定义域名： data.service.invest.smoothnlp.com/ 
 *
 * OpenAPI spec version: 2019-08-27 14:25:56
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Investment) {
      root.Investment = {};
    }
    root.Investment.InvestmentApi = factory(root.Investment.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Investment service.
   * @module api/InvestmentApi
   * @version 2019-08-27 14:25:56
   */

  /**
   * Constructs a new InvestmentApi. 
   * @alias module:api/InvestmentApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getInvestment operation.
     * @callback module:api/InvestmentApi~getInvestmentCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 投资事件查询
     * 投资事件查询, 通用接口. 
     * @param {Object} opts Optional parameters
     * @param {String} opts.cate1 行业一级类目 (default to )
     * @param {String} opts.cate2 行业二级类目 (default to )
     * @param {String} opts.companyName 企业工商名称 (default to )
     * @param {String} opts.productName 项目名称 (default to )
     * @param {String} opts.year 融资年份 (default to )
     * @param {module:api/InvestmentApi~getInvestmentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.getInvestment = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'cate1': opts['cate1'],
        'cate2': opts['cate2'],
        'company_name': opts['companyName'],
        'product_name': opts['productName'],
        'year': opts['year'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['HTML'];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/investment', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
