/**
 * Company
 * 企业相关信息 - 工商  * 默认域名： service-1ffy5rfz-1259459016.ap-shanghai.apigateway.myqcloud.com/release * 自定义域名： data.service.company.smoothnlp.com/ 
 *
 * OpenAPI spec version: 2019-09-04 17:44:33
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Company);
  }
}(this, function(expect, Company) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Company.CompanyApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanyApi', function() {
    describe('getCompanyExact', function() {
      it('should call getCompanyExact successfully', function(done) {
        //uncomment below and update the code to test getCompanyExact
        //instance.getCompanyExact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCompanyFuzzy', function() {
      it('should call getCompanyFuzzy successfully', function(done) {
        //uncomment below and update the code to test getCompanyFuzzy
        //instance.getCompanyFuzzy(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
